services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: helpdesk-system-app
    container_name: helpdesk-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - helpdesk-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: helpdesk-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - helpdesk-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: helpdesk-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    driver: bridge

volumes:
  db_data:
